// Generated by Selenium IDE
import { Builder, By, until } from "selenium-webdriver";

describe("navigate_pages.side", function () {
    this.timeout(30000);
    let driver;
    let vars;
    beforeEach(async function () {
        driver = await new Builder().forBrowser("chrome").build();
        vars = {};
    });
    afterEach(async function () {
        await driver.quit();
    });
    it("navigate_pages.side", async function () {
        // 1 | open | /
        await driver.get("http://localhost:5173/");

        // 2 | setWindowSize | 1936x1048
        await driver.manage().window().setRect({ width: 1936, height: 1048 });

        // 3 | click | linkText=Bloggs
        await driver.wait(until.elementLocated(By.linkText("Bloggs")), 10000);
        await driver.findElement(By.linkText("Bloggs")).click();

        // 4 | click | linkText=Network
        await driver.wait(until.elementLocated(By.linkText("Network")), 10000);
        await driver.findElement(By.linkText("Network")).click();

        // 5 | click | id=dropdown
        await driver.wait(until.elementLocated(By.id("dropdown")), 10000);
        await driver.findElement(By.id("dropdown")).click();

        // 6 | click | linkText=Logout
        await driver.wait(until.elementLocated(By.linkText("Logout")), 10000);
        await driver.findElement(By.linkText("Logout")).click();

        // 7 | click | id=login_email
        await driver.wait(until.elementLocated(By.id("login_email")), 10000);
        await driver.findElement(By.id("login_email")).click();

        // 8 | type | id=login_email | gavrieltest@gmail.com
        await driver
            .findElement(By.id("login_email"))
            .sendKeys("gavrieltest@gmail.com");

        // 9 | type | id=login_password | test
        await driver.findElement(By.id("login_password")).sendKeys("test");

        // 10 | click | css=.btn
        await driver.wait(until.elementLocated(By.css(".btn")), 10000);
        await driver.findElement(By.css(".btn")).click();

        // 11 | click | css=.main-container
        await driver.wait(until.elementLocated(By.css(".main-container")), 10000);
        await driver.findElement(By.css(".main-container")).click();

        // 12 | click | linkText=Account Settings
        await driver.wait(
            until.elementLocated(By.linkText("Account Settings")),
            10000
        );
        await driver.findElement(By.linkText("Account Settings")).click();

        // Removed mouseOver/mouseOut steps unless they're essential for the test

        // 15 | click | css=.nav-toast-button
        await driver.wait(until.elementLocated(By.css(".nav-toast-button")), 10000);
        await driver.findElement(By.css(".nav-toast-button")).click();

        // 16 | click | linkText=Bloggs
        await driver.wait(until.elementLocated(By.linkText("Bloggs")), 10000);
        await driver.findElement(By.linkText("Bloggs")).click();

        // 17 | click | linkText=Network
        await driver.wait(until.elementLocated(By.linkText("Network")), 10000);
        await driver.findElement(By.linkText("Network")).click();

        // 18 | click | linkText=Admin
        await driver.wait(until.elementLocated(By.linkText("Admin")), 10000);
        await driver.findElement(By.linkText("Admin")).click();

        // 19 | click | css=.user-title
        await driver.wait(until.elementLocated(By.css(".user-title")), 10000);
        await driver.findElement(By.css(".user-title")).click();

        // 20 | click | css=.user-next-bttn
        await driver.wait(until.elementLocated(By.css(".user-next-bttn")), 10000);
        await driver.findElement(By.css(".user-next-bttn")).click();

        // 21 | click | linkText=Admin
        await driver.wait(until.elementLocated(By.linkText("Admin")), 10000);
        await driver.findElement(By.linkText("Admin")).click();

        // 22 | click | css=.content-body
        await driver.wait(until.elementLocated(By.css(".content-body")), 10000);
        await driver.findElement(By.css(".content-body")).click();

        // 23 | click | css=.navbar > a
        await driver.wait(until.elementLocated(By.css(".navbar > a")), 10000);
        await driver.findElement(By.css(".navbar > a")).click();

        // 24 | click | linkText=Home
        await driver.wait(until.elementLocated(By.linkText("Home")), 10000);
        await driver.findElement(By.linkText("Home")).click();

        // 27 | click | linkText=Bloggs
        await driver.wait(until.elementLocated(By.linkText("Bloggs")), 10000);
        await driver.findElement(By.linkText("Bloggs")).click();

        // 28 | click | linkText=Network
        await driver.wait(until.elementLocated(By.linkText("Network")), 10000);
        await driver.findElement(By.linkText("Network")).click();

        // 29 | click | id=dropdown
        await driver.wait(until.elementLocated(By.id("dropdown")), 10000);
        await driver.findElement(By.id("dropdown")).click();

        // 30 | click | linkText=Account Settings
        await driver.wait(
            until.elementLocated(By.linkText("Account Settings")),
            10000
        );
        await driver.findElement(By.linkText("Account Settings")).click();

        // 33 | click | css=.nav-toast-button
        await driver.wait(until.elementLocated(By.css(".nav-toast-button")), 10000);
        await driver.findElement(By.css(".nav-toast-button")).click();

        // 34 | click | linkText=Logout
        await driver.wait(until.elementLocated(By.linkText("Logout")), 10000);
        await driver.findElement(By.linkText("Logout")).click();

        // 35 | click | css=p
        await driver.wait(until.elementLocated(By.css("p")), 10000);
        await driver.findElement(By.css("p")).click();

        // 36 | click | css=.register-container
        await driver.wait(
            until.elementLocated(By.css(".register-container")),
            10000
        );
        await driver.findElement(By.css(".register-container")).click();
    });
});
